language: android

jdk: oraclejdk9

env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.1
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
before_script:
  # Prepare pre-accepted licenses to not be promted at installation
  - mkdir -p "$ANDROID_HOME/licenses"
  - cp ./google-licenses/* "$ANDROID_HOME/licenses/"
  - chmod +x gradlew
script:
  - ./gradlew build check
